let libros = [
    {
    titulo: "El Quijote",
    autor: "Miguel de Cervantes",
    genero: "Ficcion",
    idioma: "Español",
    precio: 25.000,
    formato: "Tapa dura",
    isbn: "978-3-16-148410-0",
    descripcion: "Un clásico de literatura",
    estado: "Nuevo",
    ubicacion: "Madrid",
    fecha_publicacion: "1905-01-16",
    editorial: "Editorial Clasicos",
    paginas: "1072",
    dimensiones: "15x4x23cm",
    peso: "1 Kg",
    }, 
    {
    titulo: "La Odisea",
    autor: "Homero",
    genero: "Epica",
    idioma: "Griego",
    precio: 23.000,
    formato: "Tapa dura",
    isbn: "978-0-14-026886-7",
    descripcion: "Una epopeya de aventuras",
    estado: "Nuevo",
    ubicacion: "Atenas",
    fecha_publicacion: "-800-01-01",
    editorial: "Penguin Classics",
    paginas: "541",
    dimensiones: "15x3x23cm",
    peso: "0.7 Kg",
    },  
    {
    titulo: "Cien Años de Soledad",
    autor: "Gabriel García Márquez",
    genero: "Ficción",
    idioma: "Español",
    precio: 20.00,
    formato: "Tapa blanda",
    isbn: "978-0-14-310713-0",
    descripcion: "La historia de la familia Buendía.",
    estado: "Nuevo",
    ubicacion: "Bogotá",
    fecha_publicacion: "1967-05-30",
    editorial: "Editorial Sudamericana",
    paginas: "417",
    dimensiones: "13x2.5x20 cm",
    peso: "0.5 Kg",
    }, 
    {
    titulo: "Don Juan Tenorio",
    autor: "José Zorrilla",
    genero: "Drama",
    idioma: "Español",
    precio: 15.00,
    formato: "Tapa blanda",
    isbn: "978-84-376-0494-7",
    descripcion: "Una obra de teatro clásica",
    estado: "Usado",
    ubicacion: "Barcelona",
    fecha_publicacion: "1844-03-28",
    editorial: "Editorial Castalia",
    paginas: "240",
    dimensiones: "12x1.8x19 cm",
    peso: "0.3 Kg",
    }, 
    {
    titulo: "1984",
    autor: "George Orwell",
    genero: "Ciencia ficción",
    idioma: "Inglés",
    precio: 18.00,
    formato: "Tapa blanda",
    isbn: "978-0-452-28423-4",
    descripcion: "Una distopía sobre un régimen totalitario.",
    estado: "Nuevo",
    ubicacion: "Londres",
    fecha_publicacion: "1949-06-08",
    editorial: "Secker & Warburg",
    paginas: "328",
    dimensiones: "13x2x20 cm",
    peso: "0.4 kg"
    },
     {
    titulo: "Matar a un ruiseñor",
    autor: "Harper Lee",
    genero: "Ficción",
    idioma: "Inglés",
    precio: 22.00,
    formato: "Tapa blanda",
    isbn: "978-0-06-112008-4",
    descripcion: "Una historia sobre la injusticia racial.",
    estado: "Nuevo",
    ubicacion: "Nueva York",
    fecha_publicacion: "1960-07-11",
    editorial: "J.B. Lippincott & Co.",
    paginas: "281",
    dimensiones: "14x2.5x21 cm",
    peso: "0.6 kg"
    },
    {
    titulo: "El gran Gatsby",
    autor: "F. Scott Fitzgerald",
    genero: "Ficción",
    idioma: "Inglés",
    precio: 17.00,
    formato: "Tapa blanda",
    isbn: "978-0-7432-7356-5",
    descripcion: "La vida en los locos años 20.",
    estado: "Nuevo",
    ubicacion: "Nueva York",
    fecha_publicacion: "1925-04-10",
    editorial: "Charles Scribner's Sons",
    paginas: 180,
    dimensiones: "13x1.5x20 cm",
    peso: "0.3 kg"
  },
  {
    titulo: "Orgullo y Prejuicio",
    autor: "Jane Austen",
    genero: "Romántica",
    idioma: "Inglés",
    precio: 19.00,
    formato: "Tapa blanda",
    isbn: "978-1-85326-000-1",
    descripcion: "Una novela romántica clásica.",
    estado: "Nuevo",
    ubicacion: "Londres",
    fecha_publicacion: "1813-01-28",
    editorial: "T. Egerton",
    paginas: 279,
    dimensiones: "12x1.8x19 cm",
    peso: "0.35 kg"
  },
  {
    titulo: "La Odisea",
    autor: "Homero",
    genero: "Épica",
    idioma: "Griego",
    precio: 23.00,
    formato: "Tapa dura",
    isbn: "978-0-14-026886-7",
    descripcion: "Una epopeya de aventuras.",
    estado: "Nuevo",
    ubicacion: "Atenas",
    fecha_publicacion: "-800-01-01",
    editorial: "Penguin Classics",
    paginas: 541,
    dimensiones: "15x3x23 cm",
    peso: "0.7 kg"
  },
  {
    titulo: "La Divina Comedia",
    autor: "Dante Alighieri",
    genero: "Poesía",
    idioma: "Italiano",
    precio: 27.00,
    formato: "Tapa dura",
    isbn: "978-0-19-953564-4",
    descripcion: "Un viaje a través del infierno, purgatorio y paraíso.",
    estado: "Nuevo",
    ubicacion: "Florencia",
    fecha_publicacion: "1320-01-01",
    editorial: "Oxford University Press",
    paginas: 798,
    dimensiones: "14x3.5x22 cm",
    peso: "0.9 kg"
  },
  {
    titulo: "Crimen y Castigo",
    autor: "Fiódor Dostoyevski",
    genero: "Ficción",
    idioma: "Ruso",
    precio: 24.00,
    formato: "Tapa blanda",
    isbn: "978-0-14-044913-6",
    descripcion: "Un análisis profundo de la psicología humana.",
    estado: "Nuevo",
    ubicacion: "San Petersburgo",
    fecha_publicacion: "1866-01-01",
    editorial: "Penguin Classics",
    paginas: 671,
    dimensiones: "13x2.8x20 cm",
    peso: "0.5 kg"
  },
  {
    titulo: "Los Miserables",
    autor: "Victor Hugo",
    genero: "Ficción",
    idioma: "Francés",
    precio: 29.00,
    formato: "Tapa dura",
    isbn: "978-0-19-283371-5",
    descripcion: "Una obra monumental sobre la justicia social.",
    estado: "Nuevo",
    ubicacion: "París",
    fecha_publicacion: "1862-01-01",
    editorial: "Oxford University Press",
    paginas: 1463,
    dimensiones: "16x5x24 cm",
    peso: "1.5 kg"
  },
  {
    titulo: "El Retrato de Dorian Gray",
    autor: "Oscar Wilde",
    genero: "Ficción",
    idioma: "Inglés",
    precio: 16.00,
    formato: "Tapa blanda",
    isbn: "978-0-486-28473-0",
    descripcion: "Un cuento sobre la decadencia y la corrupción.",
    estado: "Nuevo",
    ubicacion: "Londres",
    fecha_publicacion: "1890-07-20",
    editorial: "Lippincott's Monthly Magazine",
    paginas: 254,
    dimensiones: "12x1.6x18 cm",
    peso: "0.3 kg"
  },
  {
    titulo: "Hamlet",
    autor: "William Shakespeare",
    genero: "Drama",
    idioma: "Inglés",
    precio: 14.00,
    formato: "Tapa blanda",
    isbn: "978-0-7434-7712-3",
    descripcion: "Una tragedia clásica.",
    estado: "Nuevo",
    ubicacion: "Londres",
    fecha_publicacion: "1603-01-01",
    editorial: "Simon & Schuster",
    paginas: 342,
    dimensiones: "13x1.9x20 cm",
    peso: "0.4 kg"
  },
  {
    titulo: "Don Quijote de la Mancha",
    autor: "Miguel de Cervantes",
    genero: "Ficción",
    idioma: "Español",
    precio: 30.00,
    formato: "Tapa dura",
    isbn: "978-0-19-953789-9",
    descripcion: "Una sátira sobre la caballería.",
    estado: "Nuevo",
    ubicacion: "Madrid",
    fecha_publicacion: "1605-01-16",
    editorial: "Oxford University Press",
    paginas: 1072,
    dimensiones: "15",
    peso: "1kg"
  },
  {
    titulo: "La Ilíada",
    autor: "Homero",
    genero: "Épica",
    idioma: "Griego",
    precio: 25.00,
    formato: "Tapa dura",
    isbn: "978-0-14-027536-0",
    descripcion: "Una epopeya de la guerra de Troya.",
    estado: "Nuevo",
    ubicacion: "Atenas",
    fecha_publicacion: "-800-01-01",
    editorial: "Penguin Classics",
    paginas: 704,
    dimensiones: "15x3x23 cm",
    peso: "0.8 kg"
  },
  {
    titulo: "Anna Karenina",
    autor: "León Tolstói",
    genero: "Ficción",
    idioma: "Ruso",
    precio: 26.00,
    formato: "Tapa blanda",
    isbn: "978-0-14-303500-8",
    descripcion: "Una historia de amor y tragedia.",
    estado: "Nuevo",
    ubicacion: "Moscú",
    fecha_publicacion: "1877-01-01",
    editorial: "Penguin Classics",
    paginas: 964,
    dimensiones: "14x3.5x22 cm",
    peso: "1 kg"
  },
  {
    titulo: "Ulises",
    autor: "James Joyce",
    genero: "Ficción",
    idioma: "Inglés",
    precio: 28.00,
    formato: "Tapa dura",
    isbn: "978-0-679-72232-3",
    descripcion: "Una obra maestra modernista.",
    estado: "Nuevo",
    ubicacion: "Dublín",
    fecha_publicacion: "1922-02-02",
    editorial: "Random House",
    paginas: 732,
    dimensiones: "16x3.8x24 cm",
    peso: "1.2 kg"
  },
  {
    titulo: "Madame Bovary",
    autor: "Gustave Flaubert",
    genero: "Ficción",
    idioma: "Francés",
    precio: 22.00,
    formato: "Tapa blanda",
    isbn: "978-0-19-953565-9",
    descripcion: "La historia de una mujer insatisfecha.",
    estado: "Nuevo",
    ubicacion: "París",
    fecha_publicacion: "1857-01-01",
    editorial: "Oxford University Press",
    paginas: 329,
    dimensiones: "13x2x20 cm",
    peso: "0.4 kg"
  },
  {
    titulo: "La Metamorfosis",
    autor: "Franz Kafka",
    genero: "Ficción",
    idioma: "Alemán",
    precio: 12.00,
    formato: "Tapa blanda",
    isbn: "978-0-14-104539-3",
    descripcion: "Un hombre se convierte en insecto.",
    estado: "Nuevo",
    ubicacion: "Praga",
    fecha_publicacion: "1915-01-01",
    editorial: "Penguin Classics",
    paginas: 201,
    dimensiones: "12x1.5x18 cm",
    peso: "0.2 kg"
  }
];

const libroEjemplo = [
    {
    titulo: "Fahrenheit 451",
    autor: "Ray Bradbury",
    genero: "Ciencia ficción",
    idioma: "Inglés",
    precio: 18.00,
    formato: "Tapa blanda",
    isbn: "978-0-7432-7356-5",
    descripcion: "Una distopía sobre una sociedad donde los libros están prohibidos.",
    estado: "Nuevo",
    ubicacion: "Los Ángeles",
    fecha_publicacion: "1953-10-19",
    editorial: "Ballantine Books",
    paginas: 256,
    dimensiones: "13x1.5x20 cm",
    peso: "0.3 kg"
    }
];

libros.push(libroEjemplo)
console.log(libros);

libros.pop()
console.log(libros);

libros.shift(libroEjemplo)
console.log(libros);








